testing anchore
UKHomeOffice/docker-sonarqube pull request #20
Opened 2019-06-25 14:47 UTC by aibitayo55555

2019-07-01 11:30 UTC, asmith030 requested changes

2019-07-01 11:30 UTC, asmith030 commented on .drone.yml
> +    tolarates: medium
tolerates rather than tolarates (Fixed in the latest version)

2019-07-01 11:30 UTC, asmith030 commented on .drone.yml
> +    fail_on_detection: false
Do we want this false?

2019-07-02 11:11 UTC, KashifSaadat approved these changes

2021-08-13 09:41 UTC, closed without merging